// rcpp readme
//
// The README states how large the curriculum is. A person typing those numbers
// gets them wrong eventually, and a claim that disagrees with the filesystem is
// exactly the drift this repository exists to prevent, so the numbers are
// generated from disk and checked in continuous integration.
//
//   rcpp readme --check   exit 1 when the README disagrees with the repository
//   rcpp readme --fix     rewrite the generated block

#include <cstring>
#include <iostream>
#include <set>
#include <sstream>

#include "atlas.hpp"
#include "catalog.hpp"
#include "commands.hpp"
#include "util.hpp"

namespace rcpp {
namespace {

const char* kBegin = "<!-- COUNTS:START (generated by rcpp readme, do not edit by hand) -->";
const char* kEnd = "<!-- COUNTS:END -->";

const char* kPhasesBegin = "<!-- PHASES:START (generated by rcpp readme, do not edit by hand) -->";
const char* kPhasesEnd = "<!-- PHASES:END -->";

std::string render_block(const Catalog& catalog, const Atlas& atlas) {
  std::set<std::string> toolchains;
  for (const auto* lesson : catalog.all())
    for (const std::string& platform : lesson->platforms) toolchains.insert(platform);

  int minutes = 0;
  for (const auto* lesson : catalog.all()) minutes += lesson->minutes;

  std::ostringstream out;
  out << kBegin << "\n";
  out << "```text\n";
  out << catalog.lesson_count() << " lessons"
      << "   " << catalog.phases.size() << " phases"
      << "   " << atlas.entries.size() << " atlas entries"
      << "   " << toolchains.size() << " toolchains claimed"
      << "   " << (minutes / 60) << " hours of material\n";
  out << "```\n";
  out << kEnd;
  return out.str();
}

// The table of what exists. It was maintained by hand and it drifted: phase 07
// was listed with two lessons after a third was added, and phase 08 was absent
// entirely with five lessons on disk. The counts beside it were generated and
// stayed correct throughout, which is the argument for generating this too.
std::string render_phases(const Catalog& catalog) {
  std::ostringstream out;
  out << kPhasesBegin << "\n";
  out << "| Phase | Lessons | Ends with |\n";
  out << "|---|---|---|\n";

  for (const Phase& phase : catalog.phases) {
    std::ostringstream number;
    number << (phase.num < 10 ? "0" : "") << phase.num;
    out << "| " << number.str() << " " << phase.title
        << " | " << phase.lessons.size()
        << " | " << phase.ends_with << " |\n";
  }
  out << kPhasesEnd;
  return out.str();
}

// Replaces one marked region, or reports what differs. Returns false when the
// README disagrees and was not rewritten.
bool sync_block(std::string& readme, const std::string& wanted, const char* begin_marker,
                const char* end_marker, bool fix, bool& changed, std::string& error) {
  const std::size_t begin = readme.find(begin_marker);
  const std::size_t end = readme.find(end_marker);
  if (begin == std::string::npos || end == std::string::npos || end < begin) {
    error = std::string("README.md has no ") + begin_marker + " block";
    return false;
  }

  const std::string present = readme.substr(begin, end + std::strlen(end_marker) - begin);
  if (present == wanted) return true;

  if (!fix) {
    error = std::string("the README disagrees with what is on disk\n\n  it says:\n") +
            present + "\n\n  the repository holds:\n" + wanted;
    return false;
  }

  readme.replace(begin, present.size(), wanted);
  changed = true;
  return true;
}

}  // namespace

int cmd_readme(const Args& args) {
  const auto root = find_repo_root();
  if (!root) {
    std::cerr << "rcpp readme: run this from inside the repository\n";
    return 2;
  }

  const fs::path readme_path = *root / "README.md";
  const auto readme = read_file(readme_path);
  if (!readme) {
    std::cerr << "rcpp readme: cannot read README.md\n";
    return 2;
  }

  const Catalog catalog = load_catalog(*root);
  const Atlas atlas = load_atlas(*root);

  const bool fix = has_flag(args, "--fix");
  std::string updated = *readme;
  bool changed = false;
  std::string error;

  if (!sync_block(updated, render_block(catalog, atlas), kBegin, kEnd, fix, changed, error) ||
      !sync_block(updated, render_phases(catalog), kPhasesBegin, kPhasesEnd, fix, changed, error)) {
    std::cout << "rcpp readme: " << error << "\n\n  run: rcpp readme --fix\n";
    return 1;
  }

  if (!changed) {
    std::cout << "rcpp readme: the counts and the phase table match the repository\n";
    return 0;
  }

  if (!write_file(readme_path, updated)) {
    std::cerr << "rcpp readme: could not write README.md\n";
    return 2;
  }
  std::cout << "rcpp readme: updated the generated sections\n";
  return 0;
}

}  // namespace rcpp
