// rcpp readme
//
// The README states how large the curriculum is. A person typing those numbers
// gets them wrong eventually, and a claim that disagrees with the filesystem is
// exactly the drift this repository exists to prevent, so the numbers are
// generated from disk and checked in continuous integration.
//
//   rcpp readme --check   exit 1 when the README disagrees with the repository
//   rcpp readme --fix     rewrite the generated block

#include <cstring>
#include <iostream>
#include <set>
#include <sstream>

#include "atlas.hpp"
#include "catalog.hpp"
#include "commands.hpp"
#include "util.hpp"

namespace rcpp {
namespace {

const char* kBegin = "<!-- COUNTS:START (generated by rcpp readme, do not edit by hand) -->";
const char* kEnd = "<!-- COUNTS:END -->";

std::string render_block(const Catalog& catalog, const Atlas& atlas) {
  std::set<std::string> toolchains;
  for (const auto* lesson : catalog.all())
    for (const std::string& platform : lesson->platforms) toolchains.insert(platform);

  int minutes = 0;
  for (const auto* lesson : catalog.all()) minutes += lesson->minutes;

  std::ostringstream out;
  out << kBegin << "\n";
  out << "```text\n";
  out << catalog.lesson_count() << " lessons"
      << "   " << catalog.phases.size() << " phases"
      << "   " << atlas.entries.size() << " atlas entries"
      << "   " << toolchains.size() << " toolchains claimed"
      << "   " << (minutes / 60) << " hours of material\n";
  out << "```\n";
  out << kEnd;
  return out.str();
}

}  // namespace

int cmd_readme(const Args& args) {
  const auto root = find_repo_root();
  if (!root) {
    std::cerr << "rcpp readme: run this from inside the repository\n";
    return 2;
  }

  const fs::path readme_path = *root / "README.md";
  const auto readme = read_file(readme_path);
  if (!readme) {
    std::cerr << "rcpp readme: cannot read README.md\n";
    return 2;
  }

  const std::size_t begin = readme->find(kBegin);
  const std::size_t end = readme->find(kEnd);
  if (begin == std::string::npos || end == std::string::npos || end < begin) {
    std::cerr << "rcpp readme: README.md has no generated block.\n"
                 "  Add these two lines where the counts belong:\n\n"
              << "    " << kBegin << "\n"
              << "    " << kEnd << "\n";
    return 2;
  }

  const Catalog catalog = load_catalog(*root);
  const Atlas atlas = load_atlas(*root);
  const std::string wanted = render_block(catalog, atlas);
  const std::string present = readme->substr(begin, end + std::strlen(kEnd) - begin);

  if (present == wanted) {
    std::cout << "rcpp readme: the counts match the repository\n";
    return 0;
  }

  if (!has_flag(args, "--fix")) {
    std::cout << "rcpp readme: the README disagrees with what is on disk\n\n"
              << "  it says:\n" << present << "\n\n"
              << "  the repository holds:\n" << wanted << "\n\n"
              << "  run: rcpp readme --fix\n";
    return 1;
  }

  std::string updated = *readme;
  updated.replace(begin, present.size(), wanted);
  if (!write_file(readme_path, updated)) {
    std::cerr << "rcpp readme: could not write README.md\n";
    return 2;
  }
  std::cout << "rcpp readme: updated the counts\n";
  return 0;
}

}  // namespace rcpp
